export const albums = [
  {
    slug: "channel-orange",
    title: "Channel Orange",
    artist: "Frank Ocean",
    releaseDate: "July 10, 2012",
    score: "9/10",
    genre: "R&B, Neo-Soul",
    length: "55:03",
    review:
      "Frank Ocean's Channel Orange remains an iconic album that transcends genre boundaries. Its intricate blend of R&B and neo-soul, paired with introspective lyrics and experimental production, creates an immersive experience. Standout tracks like 'Pyramids' and 'Thinkin Bout You' anchor the album's narrative, inviting listeners into a deeply personal and atmospheric soundscape. Channel Orange is a timeless exploration of love, longing, and the complexities of modern relationships.",
    standoutTracks: ["Pyramids", "Thinkin Bout You"],
    vibe: "Late-night drives",
    image: "/images/channel-orange.jpg",
    link: "https://open.spotify.com/album/392p3shh2jkxUxY2VHvlH8",
    youtube:
      "https://www.youtube.com/watch?v=xEQ_946TO_g&list=PLX68ZEYlh74vDJY4XR775HHifYT7IeXsj&ab_channel=FrankOcean-Topic",
    comments: [
      {
        name: "BeatLover92",
        text: "Pyramids is unreal!",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "SoulSeeker",
        text: "This album hits me every time.",
        date: "Jan 15, 2025",
        score: 9,
      },
      {
        name: "NightOwl",
        text: "Perfect for driving at 2 AM.",
        date: "Feb 10, 2025",
        score: 8,
      },
      {
        name: "R&BKing",
        text: "Thinkin Bout You is pure emotion.",
        date: "Jan 28, 2025",
        score: 10,
      },
      {
        name: "VibeChaser",
        text: "Frank’s voice is everything.",
        date: "Feb 3, 2025",
        score: 9,
      },
      {
        name: "ChillMode",
        text: "Lost in the vibes, man.",
        date: "Feb 20, 2025",
        score: 7,
      },
      {
        name: "OceanFan",
        text: "Still my favorite album ever.",
        date: "Jan 5, 2025",
        score: 10,
      },
      {
        name: "MelodyMuse",
        text: "The production is next level.",
        date: "Feb 14, 2025",
        score: 8,
      },
      {
        name: "LateNighter",
        text: "Can’t sleep without this.",
        date: "Jan 22, 2025",
        score: 9,
      },
      {
        name: "EchoEar",
        text: "Pyramids alone is worth it.",
        date: "Feb 25, 2025",
        score: 10,
      },
    ],
  },
  {
    slug: "nevermind",
    title: "Nevermind",
    artist: "Nirvana",
    releaseDate: "September 24, 1991",
    score: "8.5/10",
    genre: "Grunge, Alternative Rock",
    length: "42:38",
    review:
      "Nirvana's Nevermind redefined the music landscape of the early '90s with its raw energy and unfiltered emotion. The album's gritty guitar riffs and Cobain's anguished vocals capture the essence of grunge, making tracks like 'Smells Like Teen Spirit' and 'Come As You Are' enduring anthems. Nevermind is both a reflection of its turbulent era and a timeless work that continues to resonate with new generations of listeners.",
    standoutTracks: ["Smells Like Teen Spirit", "Come As You Are"],
    vibe: "Angsty basement jams",
    image: "/images/nevermind.jpg",
    comments: [
      {
        name: "GrungeFan",
        text: "Teen Spirit is iconic!",
        date: "Feb 26, 2025",
        score: 9,
      },
      {
        name: "RiffRocker",
        text: "Cobain’s screams are life.",
        date: "Jan 10, 2025",
        score: 8,
      },
      {
        name: "90sKid",
        text: "Takes me back every time.",
        date: "Feb 18, 2025",
        score: 10,
      },
      {
        name: "AngstLord",
        text: "Come As You Are is so raw.",
        date: "Jan 30, 2025",
        score: 9,
      },
      {
        name: "GuitarGuru",
        text: "Those riffs still slap.",
        date: "Feb 5, 2025",
        score: 8,
      },
      {
        name: "BasementBloke",
        text: "Perfect for headbanging.",
        date: "Feb 12, 2025",
        score: 7,
      },
      {
        name: "NirvanaNut",
        text: "Never gets old.",
        date: "Jan 18, 2025",
        score: 10,
      },
      {
        name: "EchoVibe",
        text: "Grunge at its finest.",
        date: "Feb 22, 2025",
        score: 9,
      },
      {
        name: "RebelSoul",
        text: "Kurt’s voice cuts deep.",
        date: "Jan 25, 2025",
        score: 8,
      },
      {
        name: "RockRager",
        text: "Still loud and proud.",
        date: "Feb 15, 2025",
        score: 9,
      },
    ],
  },
  {
    slug: "to-pimp-a-butterfly",
    title: "To Pimp a Butterfly",
    artist: "Kendrick Lamar",
    releaseDate: "March 15, 2015",
    score: "10/10",
    genre: "Hip-Hop, Jazz Rap",
    length: "78:51",
    review:
      "Kendrick Lamar's To Pimp a Butterfly is a groundbreaking album that fuses intricate lyricism with deep social and political commentary. Blending elements of jazz, funk, and spoken word, Lamar creates a rich tapestry of sound that challenges and inspires. With tracks like 'Alright' and 'King Kunta,' the album examines themes of race, identity, and empowerment in modern America, cementing its place as a monumental work in hip-hop history.",
    standoutTracks: ["Alright", "King Kunta"],
    vibe: "Revolutionary road trips",
    image: "/images/to-pimp-a-butterfly.jpg",
    comments: [
      {
        name: "HipHopHead",
        text: "Alright is my anthem.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "JazzLover",
        text: "The jazz vibes are unreal.",
        date: "Jan 12, 2025",
        score: 9,
      },
      {
        name: "TruthSpitter",
        text: "Kendrick speaks facts.",
        date: "Feb 19, 2025",
        score: 10,
      },
      {
        name: "KingKuntaFan",
        text: "King Kunta slaps hard.",
        date: "Jan 27, 2025",
        score: 9,
      },
      {
        name: "RapSage",
        text: "This album changed me.",
        date: "Feb 8, 2025",
        score: 10,
      },
      {
        name: "RoadTripper",
        text: "Perfect for the open road.",
        date: "Feb 16, 2025",
        score: 8,
      },
      {
        name: "LyricLord",
        text: "Every line hits deep.",
        date: "Jan 20, 2025",
        score: 10,
      },
      {
        name: "FunkMaster",
        text: "Funk and rap? Genius.",
        date: "Feb 23, 2025",
        score: 9,
      },
      {
        name: "RebelEar",
        text: "A revolution in sound.",
        date: "Jan 31, 2025",
        score: 10,
      },
      {
        name: "VerseVibe",
        text: "Kendrick’s best work.",
        date: "Feb 10, 2025",
        score: 9,
      },
    ],
  },
  {
    slug: "abbey-road",
    title: "Abbey Road",
    artist: "The Beatles",
    releaseDate: "September 26, 1969",
    score: "9.5/10",
    genre: "Rock, Pop",
    length: "47:23",
    review:
      "The Beatles’ Abbey Road is a timeless classic that showcases the band's creative evolution. Featuring seamlessly intertwined tracks and iconic melodies, the album stands as a testament to their artistry. Songs like 'Come Together' and 'Something' highlight the group’s innovative approach to songwriting and production. Abbey Road continues to influence and inspire musicians across generations, embodying the spirit of rock and pop excellence.",
    standoutTracks: ["Come Together", "Something"],
    vibe: "Sunny afternoon strolls",
    image: "/images/abbey-road.jpg",
    comments: [
      {
        name: "ClassicRockRulz",
        text: "Timeless vibes.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "BeatlesBae",
        text: "Come Together is perfection.",
        date: "Jan 14, 2025",
        score: 9,
      },
      {
        name: "SunnyTunes",
        text: "Great for a chill walk.",
        date: "Feb 17, 2025",
        score: 8,
      },
      {
        name: "MelodyMan",
        text: "Something is so beautiful.",
        date: "Jan 29, 2025",
        score: 10,
      },
      {
        name: "RockRoot",
        text: "The Beatles at their peak.",
        date: "Feb 6, 2025",
        score: 9,
      },
      {
        name: "RetroRocker",
        text: "Still sounds fresh.",
        date: "Feb 13, 2025",
        score: 8,
      },
      {
        name: "HarmonyHound",
        text: "Love the medley.",
        date: "Jan 23, 2025",
        score: 10,
      },
      {
        name: "PopPioneer",
        text: "A masterpiece forever.",
        date: "Feb 21, 2025",
        score: 9,
      },
      {
        name: "GrooveGuru",
        text: "Every track shines.",
        date: "Jan 16, 2025",
        score: 9,
      },
      {
        name: "StrollStar",
        text: "Sunny day essential.",
        date: "Feb 24, 2025",
        score: 8,
      },
    ],
  },
  {
    slug: "dark-side-of-the-moon",
    title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    releaseDate: "March 1, 1973",
    score: "9/10",
    genre: "Progressive Rock",
    length: "42:50",
    review:
      "Pink Floyd's The Dark Side of the Moon is a sonic journey through time and space. Merging progressive rock with experimental soundscapes, the album explores themes of existence, conflict, and mental strain. The seamless transitions between tracks and innovative use of sound effects create an immersive atmosphere that is both thought-provoking and mesmerizing. It remains a quintessential piece of musical art that challenges the boundaries of conventional rock.",
    standoutTracks: ["Time", "Money"],
    vibe: "Stargazing sessions",
    image: "/images/dark-side-of-the-moon.jpg",
    comments: [
      {
        name: "ProgRockFan",
        text: "Time is mind-blowing.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "SpaceCadet",
        text: "Perfect for stargazing.",
        date: "Jan 11, 2025",
        score: 9,
      },
      {
        name: "FloydFreak",
        text: "Money’s bassline is fire.",
        date: "Feb 20, 2025",
        score: 8,
      },
      {
        name: "CosmicEar",
        text: "This album is a trip.",
        date: "Jan 26, 2025",
        score: 10,
      },
      {
        name: "EchoDreamer",
        text: "So deep and haunting.",
        date: "Feb 7, 2025",
        score: 9,
      },
      {
        name: "NightSky",
        text: "Takes me to another world.",
        date: "Feb 14, 2025",
        score: 8,
      },
      {
        name: "SoundSage",
        text: "Production is unreal.",
        date: "Jan 19, 2025",
        score: 10,
      },
      {
        name: "MoonWalker",
        text: "A classic for a reason.",
        date: "Feb 23, 2025",
        score: 9,
      },
      {
        name: "RiffRider",
        text: "Love the transitions.",
        date: "Jan 31, 2025",
        score: 8,
      },
      {
        name: "StarGazer",
        text: "Floyd’s finest hour.",
        date: "Feb 9, 2025",
        score: 9,
      },
    ],
  },
  {
    slug: "thriller",
    title: "Thriller",
    artist: "Michael Jackson",
    releaseDate: "November 30, 1982",
    score: "8.8/10",
    genre: "Pop, Funk",
    length: "42:16",
    review:
      "Michael Jackson's Thriller is an electrifying blend of pop, funk, and rock that set new standards for mainstream music. The album's infectious grooves, groundbreaking production, and innovative music videos transformed the music industry. With unforgettable tracks like 'Billie Jean' and 'Thriller,' this album remains a cultural phenomenon, offering both danceable beats and an enduring legacy of artistic excellence.",
    standoutTracks: ["Billie Jean", "Thriller"],
    vibe: "Party all night",
    image: "/images/thriller.jpg",
    comments: [
      {
        name: "PopKingFan",
        text: "Billie Jean forever!",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "DanceMachine",
        text: "Can’t stop moving!",
        date: "Jan 13, 2025",
        score: 9,
      },
      {
        name: "MJ4Life",
        text: "Thriller vid is legendary.",
        date: "Feb 18, 2025",
        score: 10,
      },
      {
        name: "GrooveKing",
        text: "Pure dance floor gold.",
        date: "Jan 28, 2025",
        score: 8,
      },
      {
        name: "FunkSoul",
        text: "MJ’s peak right here.",
        date: "Feb 4, 2025",
        score: 9,
      },
      {
        name: "PartyPal",
        text: "Every track’s a banger.",
        date: "Feb 11, 2025",
        score: 8,
      },
      {
        name: "BeatBoss",
        text: "Billie Jean is untouchable.",
        date: "Jan 21, 2025",
        score: 10,
      },
      {
        name: "MoonwalkMan",
        text: "Still gets me hyped.",
        date: "Feb 22, 2025",
        score: 9,
      },
      {
        name: "RhythmRocker",
        text: "A pop masterpiece.",
        date: "Jan 17, 2025",
        score: 8,
      },
      {
        name: "NightJammer",
        text: "Party vibes all day.",
        date: "Feb 25, 2025",
        score: 9,
      },
    ],
  },
  {
    slug: "blonde",
    title: "Blonde",
    artist: "Frank Ocean",
    releaseDate: "August 20, 2016",
    score: "9.2/10",
    genre: "R&B, Experimental",
    length: "60:08",
    review:
      "Frank Ocean's Blonde is an ethereal and introspective album that defies conventional boundaries. With its fragmented soundscapes and raw, vulnerable lyricism, Blonde invites listeners into a deeply personal journey. The experimental production paired with haunting melodies creates an atmosphere of melancholic beauty. It’s a bold artistic statement that challenges traditional narratives in R&B, leaving a lasting impact on anyone who listens.",
    standoutTracks: ["Nikes", "Self Control"],
    vibe: "Rainy introspection",
    image: "/images/blonde.jpg",
    comments: [
      {
        name: "DreamListener",
        text: "Nikes feels like a dream.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "RainyDays",
        text: "Self Control broke me.",
        date: "Jan 15, 2025",
        score: 9,
      },
      {
        name: "SoulDrifter",
        text: "So hauntingly beautiful.",
        date: "Feb 19, 2025",
        score: 10,
      },
      {
        name: "VibeVoyager",
        text: "Frank’s a genius.",
        date: "Jan 27, 2025",
        score: 9,
      },
      {
        name: "EchoHeart",
        text: "Perfect for rainy nights.",
        date: "Feb 8, 2025",
        score: 8,
      },
      {
        name: "MoodMaker",
        text: "This album is therapy.",
        date: "Feb 16, 2025",
        score: 10,
      },
      {
        name: "SoftSounds",
        text: "Can’t get enough.",
        date: "Jan 20, 2025",
        score: 9,
      },
      {
        name: "OceanEyes",
        text: "Every listen hits different.",
        date: "Feb 23, 2025",
        score: 8,
      },
      {
        name: "ChillSeeker",
        text: "Pure introspection.",
        date: "Jan 31, 2025",
        score: 9,
      },
      {
        name: "MelancholyMuse",
        text: "Blonde’s a vibe.",
        date: "Feb 10, 2025",
        score: 10,
      },
    ],
  },
  {
    slug: "my-beautiful-dark-twisted-fantasy",
    title: "My Beautiful Dark Twisted Fantasy",
    artist: "Kanye West",
    releaseDate: "November 22, 2010",
    score: "9.8/10",
    genre: "Hip-Hop",
    length: "68:36",
    review:
      "Kanye West's My Beautiful Dark Twisted Fantasy is a monumental work in hip-hop that combines raw emotion with grandiose production. The album features a dynamic range of sounds, from orchestral arrangements to hard-hitting beats, creating a dramatic and immersive listening experience. With tracks like 'Power' and 'Runaway,' Kanye explores themes of fame, excess, and introspection with unbridled honesty. This album is a bold artistic statement that has redefined the possibilities of modern hip-hop.",
    standoutTracks: ["Power", "Runaway"],
    vibe: "Epic late-night hype",
    image: "/images/mbdtf.jpg",
    comments: [
      {
        name: "YeStan",
        text: "Runaway is art.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "HypeBeast",
        text: "Power gets me pumped!",
        date: "Jan 14, 2025",
        score: 9,
      },
      {
        name: "KanyeKrew",
        text: "This album’s a movie.",
        date: "Feb 17, 2025",
        score: 10,
      },
      {
        name: "BeatBanger",
        text: "Production is insane.",
        date: "Jan 29, 2025",
        score: 9,
      },
      {
        name: "NightRider",
        text: "Late-night perfection.",
        date: "Feb 6, 2025",
        score: 8,
      },
      {
        name: "RapRoyal",
        text: "Kanye’s best, hands down.",
        date: "Feb 13, 2025",
        score: 10,
      },
      {
        name: "VibeLord",
        text: "Runaway’s piano kills me.",
        date: "Jan 23, 2025",
        score: 9,
      },
      {
        name: "EpicEar",
        text: "So bold and wild.",
        date: "Feb 21, 2025",
        score: 8,
      },
      {
        name: "FlowFanatic",
        text: "Every track is huge.",
        date: "Jan 16, 2025",
        score: 9,
      },
      {
        name: "HypeMaster",
        text: "Still on repeat.",
        date: "Feb 24, 2025",
        score: 10,
      },
    ],
  },
  {
    slug: "ok-computer",
    title: "OK Computer",
    artist: "Radiohead",
    releaseDate: "May 21, 1997",
    score: "9.4/10",
    genre: "Rock",
    length: "53:21",
    review:
      "Radiohead's OK Computer is a seminal album that captures the anxiety and alienation of the modern era. Its intricate arrangements, haunting melodies, and innovative production create a disorienting yet captivating soundscape. With standout tracks like 'Paranoid Android' and 'Karma Police,' the album blends experimental rock with accessible songwriting, offering a profound commentary on technology and society. OK Computer remains a timeless work that continues to influence and resonate with listeners.",
    standoutTracks: ["Paranoid Android", "Karma Police"],
    vibe: "Dystopian headphone walks",
    image: "/images/ok-computer.jpg",
    comments: [
      {
        name: "RadioFan",
        text: "Karma Police hits different.",
        date: "Feb 26, 2025",
        score: 10,
      },
      {
        name: "AltRockAddict",
        text: "Paranoid Android is wild.",
        date: "Jan 12, 2025",
        score: 9,
      },
      {
        name: "HeadphoneHiker",
        text: "Perfect for dark walks.",
        date: "Feb 20, 2025",
        score: 8,
      },
      {
        name: "SoundScaper",
        text: "So ahead of its time.",
        date: "Jan 25, 2025",
        score: 10,
      },
      {
        name: "EchoEdge",
        text: "Thom’s voice haunts me.",
        date: "Feb 7, 2025",
        score: 9,
      },
      {
        name: "DystopiaDreamer",
        text: "Feels like the future.",
        date: "Feb 15, 2025",
        score: 8,
      },
      {
        name: "RockRebel",
        text: "A masterpiece of unease.",
        date: "Jan 19, 2025",
        score: 10,
      },
      {
        name: "MelodyMaverick",
        text: "Layers on layers.",
        date: "Feb 22, 2025",
        score: 9,
      },
      {
        name: "ChillCynic",
        text: "Karma Police is everything.",
        date: "Jan 30, 2025",
        score: 8,
      },
      {
        name: "SonicSeer",
        text: "Still blows my mind.",
        date: "Feb 9, 2025",
        score: 9,
      },
    ],
  },
];
