import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AlbumProvider from "./context/AlbumProvider";
import LayoutContent from "./components/LayoutContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Bolbol Picks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AlbumProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <LayoutContent>{children}</LayoutContent>
        </body>
      </AlbumProvider>
    </html>
  );
}
